### PR TITLE
Update DESCRIPTION

### PR DESCRIPTION
**Pull request by rudeboybert**
Removing duplicate ORCID

### CODE REVIEW

**Comment by rudeboybert** [comment]
@ismayc they want this up by June 30th. Are we ready to updated? I can do this, let me know. 


Dear maintainer,

Your DESCRIPTION file has an Authors@R field giving persons with
duplicated ORCID iDs:

************************************************************************
[1] "0000-0001-5093-6462"
************************************************************************

Please correct before 2024-06-30 to safely retain your package on CRAN.

Best,
-k

**Comment by ismayc** [comment]
I think we are good to go here

**Comment by rudeboybert** [comment]
@ismayc let me know if you want me to submit the update to CRAN before 6/30

**Comment by ismayc** [comment]
@rudeboybert Might as well I think. Thanks!

**Pull request merged**
