### PR TITLE
Implement the fullrange option for geom_parallel_slopes

### PR DESCRIPTION
**Pull request by wjhopper**
Allows geom_parallel_slopes to draw regression lines over the entire support of the x-axis by setting fullrange=TRUE, just like you can with geom_smooth.

While the fullrange option can be abused to extrapolate models, it is also useful in pedagogical situations where you want to show exactly what the intercept is. It's also nice to have more consistency between this function and its close cousin geom_smooth.

### CODE REVIEW

**Comment by ismayc** [comment]
This seems like a good addition to me. @echasnovski, given you wrote this implementation, do you have thoughts on adding this in?

**Comment by echasnovski** [comment]
Yes, looks like a good idea.
I have some doubts about implementation details (particularly about using `quote()`; there must be a better way), but this seems to work for now.

If you need a more detailed review with possible enhancements, I can do that only in a week or so.

**Comment by wjhopper** [comment]
The use of `quote()` is not strictly necessary; you could move the if/then switching into the `predict_per_group` function, and pass `fullrange` and `scales` into the `predict_per_group` function. I chose to set it up this way because it felt a bit silly to switch on the value of `fullrange` once per group when the  value will never change. But, it could be done either way.

**Comment by rudeboybert** [comment]
Thanks for the PR and comment @wjhopper. Would you be ok with @echasnovski branching off this PR for a code review?

**Comment by rudeboybert** [comment]
Also @wjhopper, don't forget to update in your PR:
- `NEWS.md` with a description of the change along with an @ of your GitHub username
- `DESCRIPTION` with yourself added as a `ctb` contributor

**Comment by wjhopper** [comment]
@rudeboybert PR updated; happy for @echasnovski to take it and run with it

**Comment by echasnovski** [comment]
@ismayc or @rudeboybert, could one of you, please, merge this PR? It is a little tricky to contribute to this PR directly as I don't have writing permissions to this repository.

I plan to do some refactoring to make "internal" code more similar to {ggplot2}. And also I'll add `level` argument along with `fullrange`. Is this OK with you?

**Comment by rudeboybert** [comment]
Hey @echasnovski, sorry for the permissions confusion. This PR has been merged.

As for your question, I think that any refactoring that aligns `geom_parallel_slopes()` with ggplot2 functionality is 💯 fine by us. thanks for offering your help

**Pull request merged**
